### ISSUE TITLE
Mismatch in shape when running the demo

### ISSUE THREAD

**Issue by WEIJIARONG99** [xinge008/Cylinder3D#149]
python demo_folder.py --demo-folder model_load_dir --save-folder results
demo_folder.py --demo-folder model_load_dir --save-folder results
Namespace(config_path='config/semantickitti.yaml', demo_folder='model_load_dir', demo_label_folder='', save_folder='results')
[480 360  32]
matched parameter sets: 226, and no matched: 48
Traceback (most recent call last):
  File "demo_folder.py", line 151, in <module>
    main(args)
  File "demo_folder.py", line 103, in main
    demo_dataset_loader):
  File "/home/weijiarong/anaconda3/envs/master_thesis/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/weijiarong/anaconda3/envs/master_thesis/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/weijiarong/anaconda3/envs/master_thesis/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/weijiarong/anaconda3/envs/master_thesis/lib/python3.7/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/weijiarong/anaconda3/envs/master_thesis/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/weijiarong/anaconda3/envs/master_thesis/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/weijiarong/anaconda3/envs/master_thesis/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/weijiarong/Desktop/Cylinder3D/dataloader/dataset_semantickitti.py", line 192, in __getitem__
    data = self.point_cloud_dataset[index]
  File "/home/weijiarong/Desktop/Cylinder3D/dataloader/pc_dataset.py", line 50, in __getitem__
    raw_data = np.fromfile(self.im_idx[index], dtype=np.float32).reshape((-1, 4))
ValueError: cannot reshape array of size 55885386 into shape (4)

Anyone met the similar error?

**Comment by ZixuanChen613** [comment]
I met the same error...  waiting for an answer

ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/envs/4dplsca/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/envs/4dplsca/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/envs/4dplsca/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/workspace/code/Cylinder3D/dataloader/dataset_semantickitti.py", line 192, in __getitem__
    data = self.point_cloud_dataset[index]
  File "/workspace/code/Cylinder3D/dataloader/pc_dataset.py", line 52, in __getitem__
    raw_data = np.fromfile(self.im_idx[index], dtype=np.float32).reshape((-1, 4))
ValueError: cannot reshape array of size 293 into shape (4)

**Comment by Tony-WJR** [comment]
Hey man which version of spconv did you use? I use spconv2.0+, then this error appeared; I also want to try spconv1.2.1 as they recommended, but I failed to compile that. Did you meet the same situation?

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ZixuanChen613 ***@***.***>
发送时间: Friday, June 24, 2022 4:27:49 PM
收件人: xinge008/Cylinder3D ***@***.***>
抄送: Tony-WJR ***@***.***>; Author ***@***.***>
主题: Re: [xinge008/Cylinder3D] Mismatch in shape when running the demo (Issue #149)


I met the same error... waiting for an answer

ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/opt/conda/envs/4dplsca/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
data = fetcher.fetch(index)
File "/opt/conda/envs/4dplsca/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/opt/conda/envs/4dplsca/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/workspace/code/Cylinder3D/dataloader/dataset_semantickitti.py", line 192, in getitem
data = self.point_cloud_dataset[index]
File "/workspace/code/Cylinder3D/dataloader/pc_dataset.py", line 52, in getitem
raw_data = np.fromfile(self.im_idx[index], dtype=np.float32).reshape((-1, 4))
ValueError: cannot reshape array of size 293 into shape (4)

―

**Comment by ZhouYC-X** [comment]
I encountered similar problem and solved it by "python demo_folder.py --demo-folder /mnt/data/datasets/kitti/sequences/00/velodyne/ --save-folder ./results/". Good luck.

**Comment by christophTUM** [comment]
Does anyone else still has this problem?
