### ISSUE TITLE
docker build fail at step 33

### ISSUE THREAD

**Issue by thomas-enxuli** [xinge008/Cylinder3D#153]
```
Step 33/40 : RUN python3 setup.py bdist_wheel
 ---> Running in 85988ff802dd
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.6/spconv
creating build/lib.linux-x86_64-3.6/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.6/spconv/utils
running build_ext
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found version "10.2")
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found CUDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so
-- Found cuDNN: v8.4.0  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX;7.5;7.5+PTX
-- Added CUDA NVCC flags for: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=compute_70;-gencode;arch=compute_75,code=compute_75
-- Found Torch: /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so
-- pybind11 v2.11.0 dev1
-- Found PythonInterp: /usr/bin/python3.6 (found suitable version "3.6.9", minimum required is "3.6")
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Configuring done
CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/spconv/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in src/utils/CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.

  CUDA_ARCHITECTURES is empty for target "spconv_nms".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /spconv/build/temp.linux-x86_64-3.6
[  7%] Building CXX object src/spconv/CMakeFiles/spconv.dir/all.cc.o
[ 15%] Building CUDA object src/utils/CMakeFiles/spconv_nms.dir/nms.cu.o
[ 23%] Building CXX object src/spconv/CMakeFiles/spconv.dir/indice.cc.o
[ 30%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/indice.cu.o
[ 38%] Linking CUDA shared library /spconv/build/lib.linux-x86_64-3.6/spconv/libspconv_nms.so
[ 38%] Built target spconv_nms
[ 46%] Building CXX object src/spconv/CMakeFiles/spconv.dir/reordering.cc.o
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h: In instantiation of 'void tv::check_torch_dtype(const at::Tensor&) [with T = const int]':
/spconv/include/torch_utils.h:59:23:   required from 'tv::TensorView<T> tv::torch2tv(const at::Tensor&) [with T = const int]'
/spconv/include/spconv/spconv_ops.h:91:45:   required from 'std::vector<at::Tensor> spconv::getIndicePair(at::Tensor, int64_t, std::vector<long int>, std::vector<long int>, std::vector<long int>, std::vector<long int>, std::vector<long int>, std::vector<long int>, std::vector<long int>, int64_t, int64_t) [with unsigned int NDim = 2; int64_t = long int]'
/spconv/src/spconv/all.cc:22:69:   required from here
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h: In instantiation of 'void tv::check_torch_dtype(const at::Tensor&) [with T = int]':
/spconv/include/torch_utils.h:59:23:   required from 'tv::TensorView<T> tv::torch2tv(const at::Tensor&) [with T = int]'
/spconv/include/spconv/spconv_ops.h:91:73:   required from 'std::vector<at::Tensor> spconv::getIndicePair(at::Tensor, int64_t, std::vector<long int>, std::vector<long int>, std::vector<long int>, std::vector<long int>, std::vector<long int>, std::vector<long int>, std::vector<long int>, int64_t, int64_t) [with unsigned int NDim = 2; int64_t = long int]'
/spconv/src/spconv/all.cc:22:69:   required from here
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h: In instantiation of 'void tv::check_torch_dtype(const at::Tensor&) [with T = float]':
/spconv/include/torch_utils.h:59:23:   required from 'tv::TensorView<T> tv::torch2tv(const at::Tensor&) [with T = float]'
/spconv/include/spconv/spconv_ops.h:312:44:   required from 'at::Tensor spconv::indiceConv(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int64_t, int64_t, int64_t) [with T = float; int64_t = long int]'
/spconv/src/spconv/all.cc:26:67:   required from here
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h: In instantiation of 'void tv::check_torch_dtype(const at::Tensor&) [with T = const float]':
/spconv/include/torch_utils.h:59:23:   required from 'tv::TensorView<T> tv::torch2tv(const at::Tensor&) [with T = const float]'
/spconv/include/spconv/spconv_ops.h:313:39:   required from 'at::Tensor spconv::indiceConv(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int64_t, int64_t, int64_t) [with T = float; int64_t = long int]'
/spconv/src/spconv/all.cc:26:67:   required from here
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h: In instantiation of 'void tv::check_torch_dtype(const at::Tensor&) [with T = c10::Half]':
/spconv/include/torch_utils.h:59:23:   required from 'tv::TensorView<T> tv::torch2tv(const at::Tensor&) [with T = c10::Half]'
/spconv/include/spconv/spconv_ops.h:312:44:   required from 'at::Tensor spconv::indiceConv(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int64_t, int64_t, int64_t) [with T = c10::Half; int64_t = long int]'
/spconv/src/spconv/all.cc:28:70:   required from here
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h: In instantiation of 'void tv::check_torch_dtype(const at::Tensor&) [with T = const c10::Half]':
/spconv/include/torch_utils.h:59:23:   required from 'tv::TensorView<T> tv::torch2tv(const at::Tensor&) [with T = const c10::Half]'
/spconv/include/spconv/spconv_ops.h:313:39:   required from 'at::Tensor spconv::indiceConv(at::Tensor, at::Tensor, at::Tensor, at::Tensor, int64_t, int64_t, int64_t) [with T = c10::Half; int64_t = long int]'
/spconv/src/spconv/all.cc:28:70:   required from here
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
[ 53%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 61%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 69%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
In file included from /spconv/src/utils/all.cc:15:0:
/spconv/include/spconv/nms.h: In function 'std::vector<int> spconv::rotate_non_max_suppression_cpu(pybind11::array_t<DType>, pybind11::array_t<int>, pybind11::array_t<DType>, DType)':
/spconv/include/spconv/nms.h:133:14: error: 'cout' is not a member of 'std'
         std::cout << "box i corners:" << std::endl;
              ^~~~
/spconv/include/spconv/nms.h:133:14: note: suggested alternative: 'count'
         std::cout << "box i corners:" << std::endl;
              ^~~~
              count
/spconv/include/spconv/nms.h:135:16: error: 'cout' is not a member of 'std'
           std::cout << box_corners_r(i, k, 0) << " " << box_corners_r(i, k, 1)
                ^~~~
/spconv/include/spconv/nms.h:135:16: note: suggested alternative: 'count'
           std::cout << box_corners_r(i, k, 0) << " " << box_corners_r(i, k, 1)
                ^~~~
                count
/spconv/include/spconv/nms.h:138:14: error: 'cout' is not a member of 'std'
         std::cout << "box j corners:" << std::endl;
              ^~~~
/spconv/include/spconv/nms.h:138:14: note: suggested alternative: 'count'
         std::cout << "box j corners:" << std::endl;
              ^~~~
              count
/spconv/include/spconv/nms.h:140:16: error: 'cout' is not a member of 'std'
           std::cout << box_corners_r(j, k, 0) << " " << box_corners_r(j, k, 1)
                ^~~~
/spconv/include/spconv/nms.h:140:16: note: suggested alternative: 'count'
           std::cout << box_corners_r(j, k, 0) << " " << box_corners_r(j, k, 1)
                ^~~~
                count
[ 76%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o
make[2]: *** [src/utils/CMakeFiles/spconv_utils.dir/all.cc.o] Error 1
src/utils/CMakeFiles/spconv_utils.dir/build.make:75: recipe for target 'src/utils/CMakeFiles/spconv_utils.dir/all.cc.o' failed
CMakeFiles/Makefile2:187: recipe for target 'src/utils/CMakeFiles/spconv_utils.dir/all' failed
make[1]: *** [src/utils/CMakeFiles/spconv_utils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 84%] Linking CUDA device code CMakeFiles/spconv.dir/cmake_device_link.o
[ 92%] Linking CXX shared library /spconv/build/lib.linux-x86_64-3.6/spconv/libspconv.so
[ 92%] Built target spconv
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
/spconv/build/lib.linux-x86_64-3.6
Release
Traceback (most recent call last):
  File "setup.py", line 103, in <module>
    zip_safe=False,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 87, in build_extension
    subprocess.check_call(['cmake', '--build', '.'] + build_args, cwd=self.build_temp)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--config', 'Release', '--', '-j4']' returned non-zero exit status 2.
The command '/bin/sh -c python3 setup.py bdist_wheel' returned a non-zero code: 1
```

**Comment by L-Reichardt** [comment]
Looks like the Problem is with spconv. Setup.py is calling cmake with subprocesses enabled ( '['cmake', ...,  '-j4']' ). This can be difficult to debug. My recommendation is:
- uncomment the spconv instructions in the docker file
- docker container
- modify setup.py and set '-j1'
- Attempt the spconv installation again and see if your error messages are more useful.
