### ISSUE TITLE
Environment error

### ISSUE THREAD

**Issue by YoushaaMurhij** [xinge008/Cylinder3D#4]
Can you please specify the environment that you used in more details ?
I am trying to build a conda env with python= 3.6, pytorch=1.7, and spconv=1.2.1 (cuda 11.0) with no success.

```
Namespace(config_path='config/semantickitti.yaml')
[480 360  32]
matched parameter sets: 274, and no matched: 0
Traceback (most recent call last):
  File "test_cylinder_asym.py", line 113, in <module>
    main(args)
  File "test_cylinder_asym.py", line 83, in main
    predict_labels = my_model(val_pt_fea_ten, val_grid_ten, val_batch_size)
  File "/home/*/anaconda3/envs/cylinder3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/*/cylinder_ws/Cylinder3D/network/cylinder_spconv_3d.py", line 44, in forward
    spatial_features = self.cylinder_3d_spconv_seg(features_3d, coords, batch_size)
  File "/home/*/anaconda3/envs/cylinder3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/*/cylinder_ws/Cylinder3D/network/segmentator_3d_asymm_spconv.py", line 290, in forward
    ret = self.downCntx(ret)
  File "/home/*/anaconda3/envs/cylinder3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/*/cylinder_ws/Cylinder3D/network/segmentator_3d_asymm_spconv.py", line 74, in forward
    shortcut = self.conv1(x)
  File "/home/*/anaconda3/envs/cylinder3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/*/anaconda3/envs/cylinder3d/lib/python3.6/site-packages/spconv/conv.py", line 181, in forward
    use_hash=self.use_hash)
  File "/home/*/anaconda3/envs/cylinder3d/lib/python3.6/site-packages/spconv/ops.py", line 95, in get_indice_pairs
    int(use_hash))
ValueError: /home/*/cylinder_ws/spconv/src/spconv/spconv_ops.cc 87
unknown device type
```

**Comment by xinge008** [comment]
My envirment setting is pytorch==1.3.0, spconv==1.2.1;

It seems that your error is caused by spconv, check this https://github.com/traveller59/spconv/issues/58

**Comment by YoushaaMurhij** [comment]
Thanks for your response, Which version of Cuda do you use?

**Comment by xinge008** [comment]
cuda-10.2 and cudnn 7.6

**Comment by iris0329** [comment]
I solved this problem by changing cuda version from 10.1 to 10.2

**Comment by abhigoku10** [comment]
@YoushaaMurhij @xinge008  i am having an environment of python= 3.6, pytorch=1.7, and spconv=1.2.1 with cuda =10.1 i am able to build spconv and the test the model but when i save the results i am not getting the expected results on semanttic kitti , does chaning the version of torch give different results ?

**Comment by abhigoku10** [comment]
@iris0329 @xinge008 @YoushaaMurhij  can you pls share your enivronment details python= , pytorch=, and spconv=,cuda=

**Comment by YoushaaMurhij** [comment]
> @iris0329 @xinge008 @YoushaaMurhij can you pls share your environment details python= , pytorch=, and spconv=,cuda=
I used the pre-build docker image for spconv (latest tag). I couldn't build the spconv directly

**Comment by YoushaaMurhij** [comment]
`docker pull scrin/dev-spconv`

**Comment by abhigoku10** [comment]
@YoushaaMurhij  i am able to install spconv 1.2.1 directly  but my pytorch and cuda version are not matching to the authors environment so checking to what ur complete environment which your able to run the model and obtain the results .

**Comment by YoushaaMurhij** [comment]
Unfortunately, I couldn't build the Env directly without the docker image.
The author said above that he used these setting: pytorch==1.3.0, spconv==1.2.1.

**Comment by abhigoku10** [comment]
@YoushaaMurhij  yes but he is using different cuda version to my environment due to which I think I am getting output like this #21  please have a look into this
