### ISSUE TITLE
Input Data format for spconv modules

### ISSUE THREAD

**Issue by FrancescoMandru** [xinge008/Cylinder3D#46]
I have a question regarding how to structure the point cloud in order to feed it into the spconv different modules. As the official repository seems to be inactive I'm asking you how to prepara a point cloud. That' my attempt:

```
    ptc = load_velo_scan(data[0])[:, 0:3] # Load the point cloud

    # ------------------ #
    #  Data Preparation  #
    # ------------------ #
    xyzmin = np.floor(np.percentile(ptc, 0, axis=0)).astype(np.int32)
    xyzmax = np.ceil(np.percentile(ptc, 100, axis=0)).astype(np.int32)
    ori_points = torch.tensor(ptc, requires_grad=True)
    voxel_generator = spconv.utils.VoxelGeneratorV2(voxel_size=[0.5] * 3,
                                                    point_cloud_range=[xyzmin[0], xyzmin[1], xyzmin[2], xyzmax[0], xyzmax[1], xyzmax[2]],
                                                    max_num_points=50,
                                                    max_voxels=20000,
                                                    full_mean=False)

    # ------------------------------- #
    #  Associated with compute graph  #
    # ------------------------------- #
    # 1. retain raw indice.
    ori_points_ = ori_points.detach()
    batch_point_indice = torch.arange(0, ori_points_.shape[0]).float().unsqueeze(1)  # [N, 1]
    # [N,3] -> [N,4], the add '1' is the indice in N
    ori_points_ = torch.cat((ori_points_, batch_point_indice), dim=1).view(-1, 4)
    # 2. generate voxels
    # features[num_voxels, point_per_voxel, 3+1] 1(indice), coords: [num_voxels, 1+3] 1(batch)
    # res contains:
    #   voxels: [M, max_points, ndim] float tensor. only contain points.
    #   coordinates: [M, 3] int32 tensor. zyx format.
    #   num_points_per_voxel: [M] int32 tensor.
    res = voxel_generator.generate(ori_points_.numpy())

    # https://github.com/traveller59/spconv/issues/142
    # https://github.com/traveller59/spconv/issues/188

    # features: [num_voxels, max_num_points_per_voxel, 3]
    gen_fea = torch.tensor(res['voxels'], dtype=torch.float32)
    # coors: [num_voxels, 3]
    gen_coords = torch.tensor(res['coordinates'], dtype=torch.int32)
    batch_idx = torch.zeros((gen_coords.shape[0], 1), dtype=torch.int32)  # batch=0
    gen_coords = torch.cat((batch_idx, gen_coords), dim=1)
    # # num_points: [num_voxels]
    gen_npoints = torch.tensor(res['num_points_per_voxel'], dtype=torch.int32)
    # 3. reconnect with compute graph
    gen_fea[:, :, :3] = ori_points[gen_fea[:, :, 3].long(), :]
    # # features[num_voxels, point_per_voxel, 3], N.B. set pos value to 0 in indice 0 (filling value)
    gen_fea = gen_fea[:, :, :3]
    # 4. you can do anything
    # voxel_vfe: [num_voxels, 3]
    voxel_vfe = torch.mean(gen_fea, dim=1)
    detached_vox = voxel_vfe.detach().numpy()
    spatial_shape = np.ceil(np.percentile(detached_vox, 100, axis=0) - np.percentile(detached_vox, 0, axis=0)).astype(np.int32)
    voxel_feature = spconv.SparseConvTensor(features=voxel_vfe, indices=gen_coords,
                                            spatial_shape=[400,400,400], # Don't know how to set it !!!!
                                            batch_size=1)

    simple_net = spconv.SubMConv3d(in_channels=3, out_channels=32,
                                   kernel_size=3, stride=1)
    output = simple_net(voxel_feature).dense()
```

If this procedure is not straightforward to you, cound you please provide an example of data preparing for a very simple network? Just to clarify it, thanks

**Comment by xinge008** [comment]
```python
voxel_feature = spconv.SparseConvTensor(features=voxel_vfe, indices=gen_coords,
                                            spatial_shape=[400,400,400], # Don't know how to set it !!!!
                                            batch_size=1)
```
This is the keypoint, and spatial_shape is the range of coords (larger or equal to range of coordinate).

**Comment by FrancescoMandru** [comment]
Hi @xinge008, thanks for your reply. Do you use `SparseConvTensor' in you code or you do in another way? And if you use it, Can you explain to me how do you prepare the data to be sent trought this function? Because in the original repository they use VoxelGenerator Class but I think that you do in another way. If so where I can find in your code the data preparation?

Moreover just a curiosity, I'm currently doing some tests in CPU with just one sparse convolution layer and the semantic kitti point clou and actually it crash after some seconds of processing. Is that normal in your opinion? 

The original repository is not mantained anymore i Think

**Comment by FrancescoMandru** [comment]
Hi @xinge008 pardon but I'm confused and that's the reason of my previous issue with no response, i.e understanding in detaild the dataset structured before creating the training data loader. Now I built an example following the pieces of your code and I will comment it in detail so you can follow my work:

```
  pytorch_device = torch.device('cpu:0')

  data_root = "/working_dir/data/sequences"
  data = glob.glob(os.path.join(data_root, "00/velodyne/*.bin"))
  labels = glob.glob(os.path.join(data_root, "00/labels/*.label"))

  ptc = load_velo_scan(data[0])[:10, 0:3] # Load a point cloud (N,3) format and use only 10 points for test
  lab = load_velo_label(labels[0])[:10] #Load labels (labels = np.fromfile(file, dtype=np.int32).reshape(-1, 1) & 0xFFFF that's the official indication of KITTi which is contrast with your method `nb_process_label` which require int64 anyway i cast it to 32 which should not be a probelm )

  grid_size = np.array([480, 360, 32]) # Don't know why you choose this grid size
  max_bound = np.percentile(ptc, 100, axis=0)
  min_bound = np.percentile(ptc, 0, axis=0)

  crop_range = max_bound - min_bound
  cur_grid_size = grid_size - 1

  intervals = crop_range / cur_grid_size
  grid_ind = (np.floor((np.clip(ptc, min_bound, max_bound) - min_bound) / intervals)).astype(np.int32)

  # process voxel position
  voxel_position = np.zeros(grid_size, dtype=np.float32)
  dim_array = np.ones(len(grid_size) + 1, dtype=np.int32)
  dim_array[0] = -1
  voxel_position = np.indices(grid_size) * intervals.reshape(dim_array) + min_bound.reshape(dim_array)

  # process labels
  processed_label = np.ones(grid_size, dtype=np.uint8) * 255 # Why????
  label_voxel_pair = np.concatenate([grid_ind, lab], axis=1)
  label_voxel_pair = label_voxel_pair[np.lexsort((grid_ind[:, 0], grid_ind[:, 1], grid_ind[:, 2])), :]
  processed_label = nb_process_label(np.copy(processed_label), label_voxel_pair)

  data_tuple = (voxel_position, processed_label)

  # center data on each voxel for PTnet
  voxel_centers = (grid_ind.astype(np.float32) + 0.5) * intervals + min_bound
  return_xyz = ptc - voxel_centers
  return_xyz = np.concatenate((return_xyz, ptc), axis=1)

  return_fea = return_xyz

  data_tuple += (grid_ind, lab, return_fea) # That's what you feed inside the DataLoader

  train_dataset_loader = torch.utils.data.DataLoader(dataset=data_tuple,
                                                     batch_size=1,
                                                     collate_fn=collate_fn_BEV,
                                                     shuffle=False,
                                                     num_workers=1)

  for i_iter, (_, train_vox_label, train_grid, _, train_pt_fea) in enumerate(train_dataset_loader):
      print("Hello")
```

This for sure ha something wrong as the method `collate_fn_BEV` (which is not documented as the rest of the code) launch:

```
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/working_dir/mymodel/data_processing.py", line 23, in collate_fn_BEV
    point_label = [d[3] for d in data]
  File "/working_dir/mymodel/data_processing.py", line 23, in <listcomp>
    point_label = [d[3] for d in data]
IndexError: index 3 is out of bounds for axis 0 with size 3
```

Can you help me? Thanks

**Comment by FrancescoMandru** [comment]
@xinge008 In your opinion, suppose that I didn't voxelized my point cloud. What is `voxel_fce` and `gen_coord` ?? If I have onlu a point cloud (N, 3)
