### ISSUE TITLE
Training run - CUDA memory error 

### ISSUE THREAD

**Issue by guragamb** [xinge008/Cylinder3D#64]
Hi there! 

I was trying to run the training script for SemanticKITTI and got the following error repeatedly (my machine has multiple GPUs and I got the same error on all the GPUs individually when I set the respective GPU_ID). 

```
root@my_docker_container:~/semKITTI/Cylinder3D# bash train.sh
train_cylinder_asym.py
Namespace(config_path='config/semantickitti.yaml')
[480 360  32]
  0%|          | 0/9565 [00:00<?, ?it/s]epoch 0 iter     0, loss: 3.946

  0%|          | 1/9565 [00:13<35:30:18, 13.36s/it]Traceback (most recent call last):
  File "train_cylinder_asym.py", line 169, in <module>
    main(args)
  File "train_cylinder_asym.py", line 137, in main
    loss.backward()
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.6/dist-packages/torch/autograd/__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 844.00 MiB (GPU 0; 11.91 GiB total capacity; 9.64 GiB already allocated; 656.94 MiB free; 10.49 GiB reserved in total by PyTorch)
  0%|          | 1/9565 [00:14<39:11:05, 14.75s/it]

```
Seems like the dataset and configs are fine since it reads those in properly and starts the first epoch but then dies. Any idea what might be causing this? Thanks!

**Comment by guragamb** [comment]
Temporarily got around this by setting batch_size = 1 for training in `config/semantickitti.yaml`. Training time increases significantly given the number of iterations per epoch and number of epochs required for training. I'm looking into trying nn.DistributedDataParallel to see if a multi-GPU approach can speed up training - https://github.com/xinge008/Cylinder3D/issues/22#issuecomment-860233376.
