### ISSUE TITLE
ERROR: Unexpected segmentation fault encountered in worker.

### ISSUE THREAD

**Issue by owoshch** [xinge008/Cylinder3D#69]
Hi!

I'm trying to run validation on semanticKITI dataset using your script demo_folder.py.
I specified path to semanticKITTI in config/semantickitti_custom.yaml file and run the following command:
`python demo_folder.py --config config/semantickitti_custom.yaml --demo-folder /datasets/KITTI/dataset/sequences/ --save-folder /experiments_results/KITTI/Cylinder3D/`

While doing a forward pass, I encounter the following error: 
'ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "demo_folder.py", line 156, in <module>
    main(args)
  File "demo_folder.py", line 114, in main
    predict_labels = my_model(demo_pt_fea_ten, demo_grid_ten, demo_batch_size)
  File "/home/fkitashov/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fkitashov/Documents/repositories/Cylinder3D/network/cylinder_spconv_3d.py", line 42, in forward
    coords, features_3d = self.cylinder_3d_generator(train_pt_fea_ten, train_vox_ten)
  File "/home/fkitashov/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fkitashov/Documents/repositories/Cylinder3D/network/cylinder_fea_generator.py", line 77, in forward
    processed_cat_pt_fea = self.PPmodel(cat_pt_fea)
  File "/home/fkitashov/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fkitashov/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/fkitashov/anaconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/fkitashov/anaconda3/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 96, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/fkitashov/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
  File "/home/fkitashov/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 94154) is killed by signal: Segmentation fault. `

Have you ever encountered the same issue? I'm trying to figure out how to debug it.

My setup:
CUDA 11.1
Pytorch 1.9
Ubuntu 20.4

**Comment by owoshch** [comment]
I found out that path `--demo-folder` shoul contain the path to the folder with lidar scans, not the root KITTI folder. 
I tweaked the command and it executed successfully: `python demo_folder.py --config config/semantickitti_custom.yaml --demo-folder /datasets/KITTI/dataset/sequences/08/velodyne/ --save-folder /experiments_results/KITTI/Cylinder3D/sequences/08/predictions/ --demo-label-folder /datasets/KITTI/dataset/sequences/08/labels/`

I got the following metrics:

Validation per class iou: 
car : 97.12%
bicycle : 54.47%
motorcycle : 80.87%
truck : 85.11%
bus : 70.34%
person : 76.48%
bicyclist : 92.21%
motorcyclist : 0.02%
road : 94.58%
parking : 44.84%
sidewalk : 81.19%
other-ground : 0.95%
building : 90.48%
fence : 58.71%
vegetation : 86.64%
trunk : 70.82%
terrain : 70.48%
pole : 64.23%
traffic-sign : 51.80%
Current val miou is 66.912
Current val loss is 0.739


Closing the issue.
