### ISSUE TITLE
[ERROR] The command '/bin/sh -c python3 setup.py bdist_wheel' returned a non-zero code: 1

### ISSUE THREAD

**Issue by adrianezquerro** [xinge008/Cylinder3D#93]
Hi, I have chosen to start the installation of your project again, and I have decided to clone the repository and run the dockerfile, but now I get this error. I am trying this from ubuntu 20.04

```
Step 30/36 : RUN python3 setup.py bdist_wheel
 ---> Running in cfbd7cd5bab2
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
creating build/lib.linux-x86_64-3.6/spconv
copying spconv/__init__.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/test_utils.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/conv.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/pool.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/functional.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/modules.py -> build/lib.linux-x86_64-3.6/spconv
copying spconv/ops.py -> build/lib.linux-x86_64-3.6/spconv
creating build/lib.linux-x86_64-3.6/spconv/utils
copying spconv/utils/__init__.py -> build/lib.linux-x86_64-3.6/spconv/utils
running build_ext
-- The CXX compiler identification is GNU 7.5.0
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc - skipped
-- Detecting CUDA compile features
-- Detecting CUDA compile features - done
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- Caffe2: CUDA detected: 10.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 10.2
-- Found CUDNN: /usr/lib/x86_64-linux-gnu/libcudnn.so  
-- Found cuDNN: v8.2.4  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.5;5.0;5.2;6.0;6.1;7.0;7.0+PTX;7.5;7.5+PTX
-- Added CUDA NVCC flags for: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_70,code=compute_70;-gencode;arch=compute_75,code=compute_75
-- Found Torch: /usr/local/lib/python3.6/dist-packages/torch/lib/libtorch.so  
CMake Error at CMakeLists.txt:28 (add_subdirectory):
  The source directory 
/spconv/third_party/pybind11

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
See also "/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeOutput.log".
See also "/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log".
/spconv/build/lib.linux-x86_64-3.6
Release
Traceback (most recent call last):
  File "setup.py", line 103, in <module>
    zip_safe=False,
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 204, in run
    self.run_command('build')
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 39, in run
    self.build_extension(ext)
  File "setup.py", line 71, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/spconv', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/spconv/build/lib.linux-x86_64-3.6/spconv', '-DCMAKE_PREFIX_PATH=/usr/local/lib/python3.6/dist-packages/torch', '-DPYBIND11_PYTHON_VERSION=3.6', '-DSPCONV_BuildTests=OFF', '-DCMAKE_CUDA_FLAGS="--expt-relaxed-constexpr"', '-DCMAKE_BUILD_TYPE=Release', '-DCMAKE_CUDA_COMPILER:FILEPATH=/usr/local/cuda/bin/nvcc']' returned non-zero exit status 1.
The command '/bin/sh -c python3 setup.py bdist_wheel' returned a non-zero code: 1

```
I have tried looking at the error file that points me to "/spconv/build/temp.linux-x86_64-3.6/CMakeFiles/CMakeError.log", but it is non-existent. Thank you.

**Comment by xinge008** [comment]
@derkaczda  Did you encounter this error before when running this dockerfile?

**Comment by derkaczda** [comment]
Seems like the third_party folder was removed from the spconv Github, you could try to add `git submodule update --init --recursive` after line 34 in the Dockerfile or you change the spconv repo to my fork https://github.com/derkaczda/spconv

**Comment by adrianezquerro** [comment]
> Seems like the third_party folder was removed from the spconv Github, you could try to add `git submodule update --init --recursive` after line 34 in the Dockerfile or you change the spconv repo to my fork https://github.com/derkaczda/spconv. If I find the time I can try to update the Dockerfile and make a pull request.

I tried adding "git submodule update --init --recursive" after line 34 and I get this error. 

```
In file included from /spconv/include/spconv/pool_ops.h:21:0,
                 from /spconv/src/spconv/all.cc:17:
/spconv/include/torch_utils.h:30:22: warning: 'at::DeprecatedTypeProperties& at::Tensor::type() const' is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   switch (tensor.type().scalarType()) {
           ~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Tensor.h:3:0,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/Context.h:4,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/ATen/ATen.h:5,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /usr/local/lib/python3.6/dist-packages/torch/include/torch/script.h:3,
                 from /spconv/src/spconv/all.cc:16:
/usr/local/lib/python3.6/dist-packages/torch/include/ATen/core/TensorBody.h:268:30: note: declared here
   DeprecatedTypeProperties & type() const {
                              ^~~~
[ 53%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/reordering.cu.o
[ 61%] Building CXX object src/spconv/CMakeFiles/spconv.dir/maxpool.cc.o
[ 69%] Building CUDA object src/spconv/CMakeFiles/spconv.dir/maxpool.cu.o
[ 76%] Building CXX object src/utils/CMakeFiles/spconv_utils.dir/all.cc.o
[ 84%] Linking CUDA device code CMakeFiles/spconv.dir/cmake_device_link.o
[ 92%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/libspconv.so
[ 92%] Built target spconv
[100%] Linking CXX shared library ../../../lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so
[100%] Built target spconv_utils
/spconv/build/lib.linux-x86_64-3.6
Release
installing to build/bdist.linux-x86_64/wheel
running install
running install_lib
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/wheel
creating build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/functional.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/libspconv_nms.so.1 -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/ops.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/__init__.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1.0 -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/libspconv_nms.so -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/libspconv_nms.so.1.0 -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/test_utils.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/libspconv.so -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/pool.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/modules.py -> build/bdist.linux-x86_64/wheel/spconv
creating build/bdist.linux-x86_64/wheel/spconv/utils
copying build/lib.linux-x86_64-3.6/spconv/utils/__init__.py -> build/bdist.linux-x86_64/wheel/spconv/utils
copying build/lib.linux-x86_64-3.6/spconv/conv.py -> build/bdist.linux-x86_64/wheel/spconv
copying build/lib.linux-x86_64-3.6/spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1 -> build/bdist.linux-x86_64/wheel/spconv
running install_egg_info
running egg_info
creating spconv.egg-info
writing spconv.egg-info/PKG-INFO
writing dependency_links to spconv.egg-info/dependency_links.txt
writing top-level names to spconv.egg-info/top_level.txt
writing manifest file 'spconv.egg-info/SOURCES.txt'
reading manifest file 'spconv.egg-info/SOURCES.txt'
writing manifest file 'spconv.egg-info/SOURCES.txt'
Copying spconv.egg-info to build/bdist.linux-x86_64/wheel/spconv-1.0.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/spconv-1.0.dist-info/WHEEL
creating '/spconv/dist/spconv-1.0-cp36-cp36m-linux_x86_64.whl' and adding '.' to it
adding 'spconv/__init__.py'
adding 'spconv/conv.py'
adding 'spconv/functional.py'
adding 'spconv/libspconv.so'
adding 'spconv/libspconv_nms.so'
adding 'spconv/libspconv_nms.so.1'
adding 'spconv/libspconv_nms.so.1.0'
adding 'spconv/modules.py'
adding 'spconv/ops.py'
adding 'spconv/pool.py'
adding 'spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so'
adding 'spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1'
adding 'spconv/spconv_utils.cpython-36m-x86_64-linux-gnu.so.1.0'
adding 'spconv/test_utils.py'
adding 'spconv/utils/__init__.py'
adding 'spconv-1.0.dist-info/DESCRIPTION.rst'
adding 'spconv-1.0.dist-info/metadata.json'
adding 'spconv-1.0.dist-info/top_level.txt'
adding 'spconv-1.0.dist-info/WHEEL'
adding 'spconv-1.0.dist-info/METADATA'
adding 'spconv-1.0.dist-info/RECORD'
Removing intermediate container 5087c42ec3ed
 ---> c95a7a5b312a
Step 32/37 : WORKDIR /spconv/dist
 ---> Running in 618d867b58c4
Removing intermediate container 618d867b58c4
 ---> 470b9cda8a8f
Step 33/37 : RUN pip3 install *.whl
 ---> Running in 8cdc00fe28e6
Processing ./spconv-1.0-cp36-cp36m-linux_x86_64.whl
Installing collected packages: spconv
Successfully installed spconv-1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 8cdc00fe28e6
 ---> 2db6a286af89
Step 34/37 : RUN git clone --recursive --depth 1 https://github.com/xinge008/Cylinder3D
 ---> Running in c81798688302
Cloning into 'Cylinder3D'...
Removing intermediate container c81798688302
 ---> 767c9258f6eb
Step 35/37 : WORKDIR /cylinder3d
 ---> Running in d21f6854fb88
Removing intermediate container d21f6854fb88
 ---> fa4ef1c075d1
Step 36/37 : RUN chmod +x train_nusc.sh
 ---> Running in b0438e23986a
chmod: cannot access 'train_nusc.sh': No such file or directory
The command '/bin/sh -c chmod +x train_nusc.sh' returned a non-zero code: 1

```

After showing this error message I gave train.sh and train_nusc.sh file execution permissions, but it doesn't work. 
These are my containers, may they can help you. I am really looking forward to hearing from you.
```

root@v:/home/v/Escritorio# docker ps -a
CONTAINER ID   IMAGE          COMMAND                  CREATED          STATUS                      PORTS     NAMES
e03a105cfd95   fa4ef1c075d1   "/bin/sh -c 'chmod +…"   7 minutes ago    Exited (1) 7 minutes ago              quirky_hofstadter
09cf18094b4e   fa4ef1c075d1   "/bin/sh -c 'chmod +…"   8 minutes ago    Exited (1) 8 minutes ago              musing_kepler
b0438e23986a   fa4ef1c075d1   "/bin/sh -c 'chmod +…"   10 minutes ago   Exited (1) 10 minutes ago             sleepy_gauss
root@v:/home/v/Escritorio# docker start e03a105cfd95
e03a105cfd95
```

**Comment by derkaczda** [comment]
To be able to access the GPU inside the Docker container you need to install the nvidia-docker toolkit and use `docker run -it --gpus all <containerid> /bin/bash`. About the disappeared commands in the last part that is normal because Docker container are not persistent and therefore will always delete your history and non saved states. If you want to have your data to be persistent you need to use docker volumes or commit your changes with `docker commit`.

**Comment by adrianezquerro** [comment]
> To be able to access the GPU inside the Docker container you need to install the nvidia-docker toolkit and use `docker run -it --gpus all <containerid> /bin/bash`. About the disappeared commands in the last part that is normal because Docker container are not persistent and therefore will always delete your history and non saved states. If you want to have your data to be persistent you need to use docker volumes or commit your changes with `docker commit`. About the first problem with the missing `train_nusc.sh` I need to investigate why this is the case.

Hi again, I follow you instructions and it runs propertly on docker, reading the Nvidia GPU. But it doesn't work, and the error refers to the information I attached below.

```
root@4f58678e1237:/spconv/dist/Cylinder3D# python3 demo_folder.py --demo-folder . --save-folder .
demo_folder.py --demo-folder . --save-folder .
Namespace(config_path='config/semantickitti.yaml', demo_folder='.', demo_label_folder='', save_folder='.')
[480 360  32]
Traceback (most recent call last):
  File "demo_folder.py", line 151, in <module>
    main(args)
  File "demo_folder.py", line 103, in main
    demo_dataset_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.6/dist-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/spconv/dist/Cylinder3D/dataloader/dataset_semantickitti.py", line 192, in __getitem__
    data = self.point_cloud_dataset[index]
  File "/spconv/dist/Cylinder3D/dataloader/pc_dataset.py", line 50, in __getitem__
    raw_data = np.fromfile(self.im_idx[index], dtype=np.float32).reshape((-1, 4))
ValueError: cannot reshape array of size 15 into shape (4)

```
Now I feel really lost about this. Could you explain the reasons of the errors? It would be great. 
Thank you for the attention you are giving me.

**Comment by derkaczda** [comment]
I never used the `demo_folder.py` script, what data are you using? Are you sure the data is accessible in the container?

**Comment by alkovacs28** [comment]
> I never used the `demo_folder.py` script, what data are you using? Are you sure the data is accessible in the container?

If I have not misunderstood the project, I can run the data contained in it in the DataLoader folder or indicate other data to it myself.
In this case I just want to check how the project works and I thought that for this I had to run the demo_folder.py file.

Thank you.

**Comment by adrianezquerro** [comment]
> I never used the `demo_folder.py` script, what data are you using? Are you sure the data is accessible in the container?

If I have not misunderstood the project, I can run the data contained in it in the DataLoader folder or indicate other data to it myself.
In this case I just want to check how the project works and I thought that for this I had to run the demo_folder.py file.

Thank you.

**Comment by derkaczda** [comment]
which data in the dataloader folder do you mean there is no data in the dataloader folder? Do you want to use semanticKITTI or nuScenes or a custom dataset?

**Comment by adrianezquerro** [comment]
> which data in the dataloader folder do you mean there is no data in the dataloader folder? Do you want to use semanticKITTI or nuScenes or a custom dataset?

I want to use SemantticKitti or NuScenes, or a dataset of my own. I have tried to do it with my own data but Cuda runs out of memory.
What are the requirements to be able to run it? Both from Cuda and the dataset that I have to pass (size, format ...)

**Comment by derkaczda** [comment]
On my side for nuScenes batch size of 1 takes about 7.5GB of gpu memory, so you should have at least 8GB of gpu memory

**Comment by adrianezquerro** [comment]
> On my side for nuScenes batch size of 1 takes about 7.5GB of gpu memory, so you should have at least 8GB of gpu memory

Hi again.
I am having problems executing the datasets. I want to insert my own datasets to the trained model and know that it returns me with these models, both semanticKitti and nuscenes. What should I introduce to the terminal to be able to see results?

I want to use a file called "car.obj" whose size is 17 megabytes, which contains LIDAR 3D data.
Thanks for your answer.

**Comment by rohithsaro** [comment]
@adrianezquerro 

Could you show me how you managed to run it on a custom dataset ? 
What all changes did you have to do ? 

Your help will be greatly appreciated :)
