### ISSUE TITLE
[ERROR] RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by adrianezquerro** [xinge008/Cylinder3D#96]
Hi everyone. I have run this project passing lidar data from semantickitti to the project. I am using an nvidia GPU that is 2GB, and I am getting the following error

```
Namespace(config_path='config/semantickitti.yaml', demo_folder='test', demo_label_folder='', save_folder='/home/adrianpanoimagen/Cylinder3D/saves')
[480 360  32]
matched parameter sets: 274, and no matched: 0
Traceback (most recent call last):
  File "demo_folder.py", line 151, in <module>
    main(args)
  File "demo_folder.py", line 109, in main
    predict_labels = my_model(demo_pt_fea_ten, demo_grid_ten, demo_batch_size)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/spconv/dist/Cylinder3D/network/cylinder_spconv_3d.py", line 42, in forward
    coords, features_3d = self.cylinder_3d_generator(train_pt_fea_ten, train_vox_ten)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/spconv/dist/Cylinder3D/network/cylinder_fea_generator.py", line 77, in forward
    processed_cat_pt_fea = self.PPmodel(cat_pt_fea)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2016, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: CUDA out of memory. Tried to allocate 268.00 MiB (GPU 0; 1.95 GiB total capacity; 678.95 MiB already allocated; 184.75 MiB free; 720.00 MiB reserved in total by PyTorch)
```

I wanted to do these three things, but unfortunately I am not sure how I can do them. They are as follows:
1-Reduce batch-size. This I have tried to do from semantic-kitti.yaml, going down from 2 to 1, but I don't know if that is what I have to modify, since the result I get is the same.

2-Clear the pytorch cache. I don't know how to do this, since I try to do it from the python console and I don't get anything.

3-Indicate cpu to pytorch, instead of using the graphics card. I have tried modifying "demo_folder.py" and putting this `pytorch_device = torch.device ("cpu"),` but nothing changes. can anybody help me? Thanks

**Comment by xinge008** [comment]
It is better to increase your GPU memory. 2GB is too small for the modern networks, especially for the large-scale point clouds.
